### ISSUE TITLE
Question about "bounds"

### ISSUE THREAD

**Issue by DigoDF** [JeanExtreme002/FlightRadarAPI#1]
Hello Jean, how are you? Hope you doing fine.
I’m a fellow brazilian too! Writing in english because more people may have the same question.

Well, first of all congratulations for the API, it’s very good! 
I came across your API few days ago and I’m trying to use it, but I have a question, I tried to find your e-mail on github, but I coudn’t. 

But, here’s my question: Do you know why “bounds” only return two points? I mean, two pairs os coordinates: latitude and longitude? I mean, in my understanding, bounds of a country, for example, should be at least four points (four pair of coordinates), so that a square area could be drawn, and this would represent a country or a continent. Maybe, these bounds are used in a certain way in aviation that I don’t know about...

I’m interested in planes that only fly above a certain area, and I’m trying do use “bounds” to limit this area. I hope I was clear!

**Comment by JeanExtreme002** [comment]
Hello @DigoDF, how are you? I tested the method `get_bounds` using the code below and it returned 4 points, separated by a comma.

```
zone = fr_api.get_zones()["southamerica"]
bounds = fr_api.get_bounds(zone)
print("Bounds of South America:", bounds) # Bounds of South America: 16,-96,-57,-31
```

**Comment by JeanExtreme002** [comment]
Hello @DigoDF, how are you. Sorry for the delay. Can you show the code you are running?

**Comment by JeanExtreme002** [comment]
Hello @DigoDF, how are you. Sorry for the delay. FlightRadar24 works with the coordinate system "y1, x1, y2, x2, y2" to create a square of the area. For this reason, the API only returns 4 values.

**Comment by JeanExtreme002** [comment]
Hello @DigoDF, how are you. Sorry for the delay. FlightRadar24 works with the coordinate system "y1, x1, y2, x2, y2" to create a square of the area. To make it easier to understand, think of it as the coordinates of a rectangle created in a graphical interface.

```
x1=(-96)
y1=16   ___________________
       |                   |
       |                   |
       |                   |
       |   SOUTH AMERICA   |
       |                   |
       |                   |
       |___________________| x2=(-31)
                             y2=(-57)
```

For this reason, the API only returns 4 values.

**Comment by DigoDF** [comment]
Hey Jean! 
I'm Fine! Thanks for your answer! 

After a while I figure it out too! There's nothing wrong with the return, it's exactly what you said! Thanks!
