### ISSUE TITLE
flight details Problem

### ISSUE THREAD

**Issue by nibog001** [JeanExtreme002/FlightRadarAPI#11]
details = fr_api.get_flight_details(flight_id="B738")
    flight.set_flight_details(details)
    print("Flying to", flight.destination_airport_name)

for this api call i get an unresolved reference 'flight' how do the flight detail calls work?

**Comment by JeanExtreme002** [comment]
The `flight_id` is not the aircraft name but an ID created by FlightRadar24 do identify each flight. Example:

random_flight = fr_api.get_flights()[0]
print("The ID for this flight is:", random_flight.id)  # The ID for this flight is: 2af43d19

details = fr_api.get_flight_details(flight_id= random_flight.id)
random_flight.set_flight_details(details)

**Comment by nibog001** [comment]
Is there a way to find the flight_id for a certain flight?
I scanned an area for flights and got a list and now I want to get details of the flights in this list

**Comment by JeanExtreme002** [comment]
Such as the sample above, each `flight` object has the attribute `id`.

**Comment by nibog001** [comment]
Thank you very much for helping very much appreciated :)

**Comment by nibog001** [comment]
```
random_flight = fr_api.get_flights()[0]
    print("The ID for this flight is:", random_flight.id)
    details = fr_api.get_flight_details(random_flight.id)
    random_flight.set_flight_details(details)
    print("Flying to", random_flight.destination_airport_name)
```
I tried getting the flights destination but get an attribute error
`AttributeError: 'NoneType' object has no attribute 'get'`
but if i try to get the Altitude
`print(random_flight.get_altitude())`
I get the actual height
