### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by gulo101** [JeanExtreme002/FlightRadarAPI#15]
Hello

How do you authenticate with your flight radar username and password?

**Comment by JeanExtreme002** [comment]
You don't need to authenticate for using this application.

**Comment by gulo101** [comment]
Sorry, I see that now. How does it know that I have a business account then? Or is this not using my FR24 account at all? Thank you

**Comment by JeanExtreme002** [comment]
For now this API doesn't support Flightradar24 accounts. If you want to use your account, you must contract the services of the website.

**Comment by gulo101** [comment]
Thank you, As long as it works without account that's all I needed. Thank you for your help.
