### ISSUE TITLE
Getting flight by registration number

### ISSUE THREAD

**Issue by miag676** [JeanExtreme002/FlightRadarAPI#19]
Hello,

firsty, I would like to thank you for creating FlightRadarAPI. My question is whether it is possible to get a flight from the list of flights by its registration number?

Also, I tried this basic example:
```
from FlightRadar24.api import FlightRadar24API
fr_api = FlightRadar24API()

flights = fr_api.get_flights()

for flight in flights:
    print(flight)
    details = fr_api.get_flight_details(flight.id)
    flight.set_flight_details(details)
    print("Flying to", flight.destination_airport_name)
```
But I get the following error on the fourt flight in the loop:
```
<(BALL) N256TH - Altitude: 59400 - Ground Speed: 8 - Heading: 305>
Traceback (most recent call last):
  File "C:\Users\uporabnik\prog\letalo.py", line 9, in <module>
    flight.set_flight_details(details)
  File "C:\Users\uporabnik\AppData\Local\Programs\Python\Python310\lib\site-packages\FlightRadar24\flight.py", line 102, in set_flight_details
    dest_aiport_code = dest_aiport.get("code", dict())
AttributeError: 'NoneType' object has no attribute 'get'
```

Do you know what might be causing it?

I will appreciate any help!

**Comment by JeanExtreme002** [comment]
The problem is a ball doesn't have airport information (I really didn't expect it). Well, for now, you can just check if `flight` is a ball or not. I'm going to fix it and update the project later. Thank you so much for your report ;)

**Comment by miag676** [comment]
Thank you for your answer!

**Comment by JeanExtreme002** [comment]
Fixed! =)
