### ISSUE TITLE
is there a typo in "self.origin_aiport_iata..." in flight.py ?

### ISSUE THREAD

**Issue by froderi1** [JeanExtreme002/FlightRadarAPI#2]
This is not a bug, but is is confusing. I ma sure the intention was this to be named
"self.origin_airport_iata = self.__get_info(info[11])"

Thanks for this great module.

**Comment by JeanExtreme002** [comment]
Yes, that was a typo and has just been fixed. Thank you very much for your attention and for reporting the error <3
