### ISSUE TITLE
set_flight_details breaks because of not existing sub-details

### ISSUE THREAD

**Issue by nitmws** [JeanExtreme002/FlightRadarAPI#20]
Executing a
`flight.set_flight_details(details)`

triggers this exception:

File "....\site-packages\FlightRadar24\flight.py", line 102, in set_flight_details
    dest_aiport_code = dest_aiport.get("code", dict())
AttributeError: 'NoneType' object has no attribute 'get'

Looking into flight.py: after
`airport = flight_details.get("airport", dict())`
a
`if airport is not None:`
is required and for all the other variables which are set by a flight_details.get() too.

**Comment by JeanExtreme002** [comment]
Thank you for your report! I just fixed it. Try it again. =)

**Comment by nitmws** [comment]
I tried it again - and got a new error:

File "....\Python39\lib\site-packages\FlightRadar24\flight.py", line 95, in set_flight_details
    aircraft = self.__get_details(flight_details.get("aircraft"))
AttributeError: 'bytes' object has no attribute 'get'

Apparently the request.content returned by FlightRadar24API.get_flight_details doesn't have the expected format.

**Comment by nitmws** [comment]
Ok, found out what the request.content is:

b'<html>\r\n<head><title>402 Payment Required</title></head>\r\n<body bgcolor="white">\r\n<center><h1>402 Payment Required</h1></center>\r\n<hr><center>nginx</center>
... etc

Apparently the FlightRadar24' API server counts accesses and shuts down after a specific count.

What is the background of your statement in the README.md:

_If you want to use the data collected using this API commercially, you need to ..._

I don't want to use the API for commercial purposes (now), I want to investigate what I can get from this API before I subscribe. And I thought the FlightRadar24API can help.
What are the limits for a "free use" by your experience?
