### ISSUE TITLE
Quota?

### ISSUE THREAD

**Issue by fmarzocca** [JeanExtreme002/FlightRadarAPI#21]
Is there a quota for retrieving flights? I always get an array of max 1500 elements.

**Comment by Gnesus** [comment]
It seems. I have the same issue

**Comment by JeanExtreme002** [comment]
This is a limit imposed by flightradar24. There's nothing we can do about it.

**Comment by karolus-git** [comment]
Sad ! Do you know if a subscription to one of their subscription plans would change that limitation?

**Comment by Gnesus** [comment]
> Sad ! Do you know if a subscription to one of their subscription plans would change that limitation?

I didn't find anything on the website reading their plans. So I don't think so, but I'm not sure. 

You can try by splitting coordinates maybe and joining the flights. But there are multiple calls. Thats the solution I thought but i've not implemented yet

**Comment by karolus-git** [comment]
Thanks for searching that! I will probably try to participate to the coverage and get a free business plan in return. If that changes anything about the API limitation, I will tell you :)

**Comment by fmarzocca** [comment]
> This is a limit imposed by flightradar24. There's nothing we can do about it.

Understand completely. But this is a great limitation to the use of the API. It doesn't make any sense to use only a subset of the flights (how this subset is defined?)...

**Comment by Gnesus** [comment]
> 

It's the first 1500 flights by coordinates. At least if you set a range of coordinates. It should work similar if you dont set a range of coords
