### ISSUE TITLE
Get flight info by flight ICAO/callsign or airplane HEX code

### ISSUE THREAD

**Issue by mfbrt** [JeanExtreme002/FlightRadarAPI#22]
Is there any way to get the flight information using the ICAO/callsign or the plane's HEX code?
Or is there a way to filter the result list using this information?

Thanks in advance.

**Comment by JeanExtreme002** [comment]
There is no way to filter flights directly from the server. Checkout this [issue](https://github.com/JeanExtreme002/FlightRadarAPI/issues/4) to understand why.

But you can filter the flight list by their attributes. Example:
```
for flight in fr_api.get_flights(airline):
    if flight.number == "QR8041": break
print("Target flight:", flight)
```

You can even use the `check_info(` method to do some stuffs like this:
```
for flight in fr_api.get_flights(airline):
    if flight.check_info(min_altitude = 6700, max_altitude = 13000, icao = "THY"): 
        break
print("Target flight:", flight)
```
