### ISSUE TITLE
Only able to retrieve 1500 flights

### ISSUE THREAD

**Issue by DanCollinsCloud** [JeanExtreme002/FlightRadarAPI#24]
Hi,

I am currently testing this excellent API and I am trying to retrieve all flights.

Although when running:

flights = fr_api.get_flights()

result = len(flights)

print(result)

It is only returning 1500. Is this customizable or is this a limit of the flightradar API?

Thanks

**Comment by JeanExtreme002** [comment]
Duplicate of #21
