### ISSUE TITLE
Accessing airline fleet information

### ISSUE THREAD

**Issue by bneogy92** [JeanExtreme002/FlightRadarAPI#25]
Hi,

I'm trying to access airline fleet information from flightradar24. I understand the API does not provide functionality as this point. Can I get some guidance as to how I can do that?

For example: airline name is WestJet, and it contains 162 aircrafts. I would need details on aircraft type and details.

Thanks a lot!

**Comment by JeanExtreme002** [comment]
I think there isn't an endpoint for airline information, but I could be wrong. At least, I have never seen it before.

**Comment by chiragshah285** [comment]
this is the link to the fleet information https://www.flightradar24.com/data/airlines/5y-gti/fleet. How are you able to discern if there is a endpoint for airline information?
