### ISSUE TITLE
Business Subscriber, How to get flights from Start Time to End Time via Get_Flights

### ISSUE THREAD

**Issue by cfernandezonesky** [JeanExtreme002/FlightRadarAPI#26]
I'm a business plan subscriber and we're having problems fetching flights from a Start Time to an End Time.
We're interested in flights from 2022-09-04 to 2022-09-05. 

Can someone elaborate how to get flights in this time frame via get_flights or any other API? 
Is there more in-depth documentation Business-Subscribers can use besides that described here? https://pypi.org/project/FlightRadarAPI/

From FlightRadar24's website we're told we get 3 years of past flight history, yet; I don't see any documentation in the API as to how to retrieve flight data well within those 3 years in the API ?? Please Help.

![image](https://user-images.githubusercontent.com/90274923/209025205-ce4456ea-5afb-4f84-892b-d9dcc350acd3.png)

**Comment by JeanExtreme002** [comment]
Sorry, but this is an unofficial API to get data from flightradar24 website for free. You should contact FlightRadar24 support for more information about their services and to resolve your issue.
