### ISSUE TITLE
bounds format for coordinates

### ISSUE THREAD

**Issue by tjirku** [JeanExtreme002/FlightRadarAPI#3]
Hi, sorry for creating an issue but i haven't found another way of getting in touch - I have a question with the "bounds" param in the get_flights() function. what type of coordinates am I supposed to use here and how can I convert these to the requested format for example for "austria" ? Any hint much appreciated...

**Comment by JeanExtreme002** [comment]
On the question of the type of coordinates, see the issue #1.

To convert the coordinates correctly, use the method `get_bounds`. You must have a dictionary with the keys `(tl_y, tl_x, br_y, br_x)` to use this method. If you don't have this dictionary, get it using the method `get_zones` or create it by entering the coordinates manually.

    zone = f.get_zones()["europe"]["subzones"]["poland"] # {'tl_y': 56.86, 'tl_x': 11.06, 'br_y': 48.22, 'br_x': 28.26}
    print(f.get_bounds(zone)) # 56.86,48.22,11.06,28.26

**Comment by tjirku** [comment]
thank you so much for your reply -
would requesting a zine like “austria” return valid bounds ?
br thomas

Jean Loui Bernard Silva de Jesus ***@***.***> schrieb am Mi.
12. Mai 2021 um 06:52:

**Comment by JeanExtreme002** [comment]
Apparently FlightRadar24 does not provide bounds for Austria.
