### ISSUE TITLE
About precision of flight position

### ISSUE THREAD

**Issue by kenzed** [JeanExtreme002/FlightRadarAPI#31]
I notice there are only 2 digits behind decimal point of latitude and longitude values in returned data. I traced the requst step of api and found there is no precision loss in data retrieving. Is it the best precision for {free, basic account} usage of FR24? Or I can get more precision with a paid FR24 account? Thank you @JeanExtreme002 and anybody else would like to write a reply.

**Comment by kenzed** [comment]
I've found out, issuse closed

**Comment by ipearx** [comment]
@kenzed what was the solution?!
