### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by mathiasdg** [JeanExtreme002/FlightRadarAPI#32]
Is there more documentation available somewhere, on how to use the API and a list of options?
eg:
`Getting flights by bounds:

bounds = fr_api.get_bounds(zone)
flights = fr_api.get_flights(bounds = bounds)`

this zone variable is not explained, which format or...?

**Comment by JeanExtreme002** [comment]
Hi @mathiasdg! You must pass the return of `get_bounds()` method to the `bounds` param.
