### ISSUE TITLE
Getting error setting details

### ISSUE THREAD

**Issue by BMKoot** [JeanExtreme002/FlightRadarAPI#33]
While getting and setting details, I sometime run into this error:

`/lib/python3.9/site-packages/FlightRadar24/flight.py", line 88, in set_flight_details
    aircraft = self.__get_details(flight_details.get("aircraft"))
AttributeError: 'bytes' object has no attribute 'get'`

I'll do some investigation to see exactly what flight this occurs on.

**Comment by Dlunhappy226** [comment]
Any source code?

**Comment by tklostermannNSD** [comment]
Got the same error for some random flights

**Comment by tklostermannNSD** [comment]
In one of the responses I got a bit of html code with HTTP 402 Payment required. Looks like we are making too much calls :(

**Comment by JeanExtreme002** [comment]
Unfortunately I didn't check this error at the time. Sorry for the delay. But the same problem happened now, with the error 520. When this happens, a [CloudflareError](https://github.com/JeanExtreme002/FlightRadarAPI/blob/334944d738a93470a5b4aa340d7db67f4e3ba0d2/FlightRadar24/request.py#L58C31-L58C31) is thrown and you can try to make a new request again after a certain period of time.
