### ISSUE TITLE
country flag wrong filetype

### ISSUE THREAD

**Issue by Xyborg** [JeanExtreme002/FlightRadarAPI#37]
https://github.com/JeanExtreme002/FlightRadarAPI/blob/e5ddbfc9ec9f4fa5bc6c2098a8f6aae35543a84c/FlightRadar24/core.py#LL32C5-L32C87

It seems country flag should be SVG instead of GIF now. Example: https://www.flightradar24.com/static/images/data/flags-small/germany.svg

**Comment by JeanExtreme002** [comment]
Thank you!
