### ISSUE TITLE
Date based queries 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [JeanExtreme002/FlightRadarAPI#4]
Hi, first of all thank you for this script. 
I was looking around and couldn't find any information on how to make date based queries, something that I'm very interested on. 
The use case would be 

**Return all flights between date 01 and date 02 for airport X.** 

I'm not looking for the number of flights but the flight details, such as airline, that occured between those dates. 

Is this possible to do with your script? 
Thank you in advance!

**Comment by JeanExtreme002** [comment]
It is not possible to filter flights or any other information by date or time through this API yet.

**Comment by JorgeMiguelGomes** [comment]
> It is not possible to filter flights or any other information by date or time through this API yet.

Is this something you are going to implement any time soon, or is it a problem that lies with FlightRadar?

**Comment by JeanExtreme002** [comment]
It is not possible for the API to filter flights in this way yet because this feature is not freely available on the FlightRadar24 website.

**Comment by JorgeMiguelGomes** [comment]
@JeanExtreme002 thank you for your time. Closing the issue.
