### ISSUE TITLE
Trying to get all a380 flights happening now (or today)

### ISSUE THREAD

**Issue by jorisfalter** [JeanExtreme002/FlightRadarAPI#41]
Hi,

I'm trying to use your api to get all a380 flights happening now (or today ideally). 

I'm doing `api.get_flights(aircraft_type = "A388")`

It seems it returns the `registration number` (as well as altitude, heading, and speed), but no flight number. Any recommended path to get all a380 flight numbers?

Many thanks!

**Comment by jktujg** [comment]
For more details you can set `details=True`
```
for flight in api.get_flights(aircraft_type="A388", details=True):
   print(flight.number)
```
Check `flight.__dict__` for other details

Or you can get raw flight details dictionary like so
```
for flight in api.get_flights(aircraft_type="A388"):
    flight_details = api.get_flight_details(flight)
```

**Comment by JeanExtreme002** [comment]
You may get the flight number by the attribute `number`.
