### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by RWayne93** [JeanExtreme002/FlightRadarAPI#45]
Are there any benefits to making this async? Was thinking of forking and making a separate branch if there was a want/need for asynchronous support.

**Comment by JeanExtreme002** [comment]
I have ever wondered about it. I think there aren't benefits, because there is a limit of requests you can do. So, a sync request should be quick enough for this case.

**Comment by JeanExtreme002** [comment]
If the website won't limit the number of requests, async methods could be a possibility.

I'm closing this issue for now.
