### ISSUE TITLE
Not working anymore ?

### ISSUE THREAD

**Issue by hubtoys** [JeanExtreme002/FlightRadarAPI#46]
**Describe the bug**
Since a few days the api does not return any results 

i’ve upgraded to the Last version with no better luck 

does anything changed ?

thanks !

**Comment by JeanExtreme002** [comment]
Hi! The code is working still. Are you getting any error?

By the way, sometimes the API may raise a CloudflareError, because you are perhaps calling the API a lots.

**Comment by hubtoys** [comment]
thanks for your answer

here is my code, called every 5 minutes, perhaps you're right (but it has been working for almost 2 years :) )

` fr_api = FlightRadar24API()
  zones = fr_api.get_zones()
  print(zones)
  bounds = fr_api.get_bounds(zones['europe'])
  flights = fr_api.get_flights(bounds=bounds)
  print(flights)`

flights remains empty

**Comment by JeanExtreme002** [comment]
I ran your code 10 times every 1 second and it returned results to me each time with no errors. Maybe a problem with your IP? Try to use a proxy.

**Comment by hubtoys** [comment]
Thanks , I will !

By the way thanks for your work !
