### ISSUE TITLE
get_flights doesn't retrieve data

### ISSUE THREAD

**Issue by Gnesus** [JeanExtreme002/FlightRadarAPI#49]
**Describe the bug**
When I use get_flights method doesn't retry any flight that it does before

**To Reproduce**
flights = fr_api.get_flights()

**Expected behavior**
A list of flight

**Screenshots**
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/6689861/1c3c9403-c239-4787-911e-f1626045fead)

**System (please complete the following information):**
 - OS: windows 10
 - Python Version 3.9 64bit

**Comment by JeanExtreme002** [comment]
Did you set any bounds or any config for the `fr_api` object? I ran tests again and it's working.

**Comment by Gnesus** [comment]
Yes, i use bounds and without bounds for testing datas:
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/6689861/67ad0435-c522-48d2-8c57-c23b407015b6)

fr_api = FlightRadar24API()
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/6689861/ad57212b-932f-44fa-a981-37b74ba7306f)

**Comment by JeanExtreme002** [comment]
The URL the package uses to get flights is https://data-cloud.flightradar24.com/zones/fcgi/feed.js. Maybe you are using a old version of the `FlightRadarAPI`?

**Comment by Gnesus** [comment]
you was right, i updated few days ago but for some reason it dowsn't i uninstalled and installed and now it works. THanks so much and sorry for the non-issue
