### ISSUE TITLE
FlightRadar documentation?

### ISSUE THREAD

**Issue by BarryPSmith** [JeanExtreme002/FlightRadarAPI#5]
Readme.md of this project suggests that FlightRadar24.com provide API access if one purchases the business plan; however there is no mention of API access on the FlightRadar24.com website at either of the links provided (https://www.flightradar24.com/premium/ or https://www.flightradar24.com/terms-and-conditions). Are you able to share where you got that information?

In a similar vein: Is the underlying API that this library uses officially documented anywhere?

**Comment by JeanExtreme002** [comment]
This project is not authored by the flightradar24 website and has no responsibility to maintain this API. This is a personal repository and the code provided here works without the need to buy anything. However, this API uses data from the flightradar24 site. For this reason, you should not use this API without first reading the flightrada24 website terms and conditions. In addition, if you want to use it commercially, you must hire the services of the flightradar24 website.

As the author of this repository, I am not responsible for any legal proceedings for the misuse of those who use this API.
