### ISSUE TITLE
Getting only first pages of arrivals/departures in airport details

### ISSUE THREAD

**Issue by Tehnik762** [JeanExtreme002/FlightRadarAPI#50]
**Is not your feature request related to a problem? Please describe**
- When looking for a details of a an airport you will get only a first page of results. 

**Additional context**
If it is ok - I am ready to do it by myself and then make PR in your project

**Comment by JeanExtreme002** [comment]
Hi @Tehnik762!

Oh yeah, I didn't notice that it's possible to get more pages by setting the param `page` on the request. Sure, you can open a PR. Something I though is allowing the param `flight_limit` be bigger than 100, and then we just divide the value by 100 (it's the limit at the back-end of the website).

**Comment by JeanExtreme002** [comment]
I accepted the PR and the feature is already on PyPI package. Again, thank you for contributing to the project! 

Closing this issue.
