### ISSUE TITLE
Get the nearest airport to a location or to a city.

### ISSUE THREAD

**Issue by ptesny** [JeanExtreme002/FlightRadarAPI#56]
**Is your feature request related to a problem? Please describe.**
Get the nearest airport to a location or to a city. Similar to how we can get flights in a given radius of for a given location.

**Is not your feature request related to a problem? Please describe**

**Additional context**

**Comment by JeanExtreme002** [comment]
Hi @ptesny ! To get the nearest airport (or even the nearest flight) from a location, you just have to create an Entity and order the list of airports by using the method `get_distance_from`, this way:

```
from FlightRadar24 import Entity, FlightRadar24API

location_coords = (34.0937508, -118.3264781)  # Hollywood coords
location = Entity(location_coords[0], location_coords[1])

fr_api = FlightRadar24API()
airports = fr_api.get_airports()

airports.sort(key=lambda airport: airport.get_distance_from(location))

print(airports[0])  # <(KBUR) Burbank Bob Hope Airport - Altitude: 778 - Latitude: 34.200661 - Longitude: -118.358002>
```

**Comment by ptesny** [comment]
Thank you @JeanExtreme002 ;  I did not realize the Entity object is also exported from the package...
How this would be in nodejs? Likely almost the same ?

PS.
It could be nice to add it as `getting-the-distance-between-cities-and-airports` similar to the following: https://github.com/JeanExtreme002/FlightRadarAPI/blob/main/python/README.md#getting-the-distance-between-flights-and-airports

**Comment by JeanExtreme002** [comment]
Yeah, it seems to be a good idea. Thanks for your report. I'll add it to the readme at the next update. 😊

I'm closing this issue for now.
