### ISSUE TITLE
getAirlineLogo does not work in nodejs

### ISSUE THREAD

**Issue by ptesny** [JeanExtreme002/FlightRadarAPI#57]
**Describe the bug**
getAirlineLogo does not work in nodejs, for instance

```
          iata =  'CDG';
          icao =  'LFPG';
          try { const airlineLogo = await frApi.getAirlineLogo(iata, icao); return airlineLogo; }
          catch (error) { console.log(error); return error.message; }

```
```
Received status code '404: Not Found' for the URL https://www.flightradar24.com/static/images/data/operators/LFPG_logo0.png
```

**Comment by JeanExtreme002** [comment]
I searched for the IATA and ICAO you are using, and they correspond to the code of the Paris Charles de Gaulle **Airport**. The method should received the IATA and ICAO of an **airline**.

**Comment by ptesny** [comment]
Thank you @JeanExtreme002 for spotting this. Indeed, the code and ICAO must be of an airline and not an airport. All good.
