### ISSUE TITLE
any documentation on the search endpoint ?

### ISSUE THREAD

**Issue by ptesny** [JeanExtreme002/FlightRadarAPI#58]
I cannot find any documentation on the search endpoint? Could you please provide a couple of examples of different search queries ? Thank you

**Comment by JeanExtreme002** [comment]
The method receives any text, such as a code of an airport or airline, or the name of an airport or airline, or the registration of an aircraft, etc. Anything. It works the same way of seaching at the search bar of the website.

```
const { FlightRadar24API } = require("flightradarapi");

const frApi = new FlightRadar24API();

async function main() { 
    const result = await frApi.search("Lukla");
    // ...
} 
main();
