### ISSUE TITLE
How to define flight in details = fr_api.get_flight_details(flight.id)? 

### ISSUE THREAD

**Issue by httpanand** [JeanExtreme002/FlightRadarAPI#6]
If flight id is QR8041 , how to define it in code ?

**Comment by JeanExtreme002** [comment]
Is it really a flight ID? It looks like a flight number. If it's not the case, use the code bellow:

    details = fr_api.get_flight_details("QR8041")

If you want to get the flight details by a flight number, callsign or anything else, you must get flights by airline or bounds and then filter them to find the correct flight. After, call the function `get_flight_details` passing the flight ID.

**Comment by httpanand** [comment]
Thank You so much

**Comment by httpanand** [comment]
Should give registration number of an aircraft? Is it same as the flight id??
