### ISSUE TITLE
Flight details dont work

### ISSUE THREAD

**Issue by DaveXDDD** [JeanExtreme002/FlightRadarAPI#60]
so i want to make the api print details about the flight, either by putting in the registration, icao or idk whatever. just so i can get info abt an exact flight. 
when i do:
flight_details = fr_api.get_flight_details(flight)
print(flight_details)

or anything in this direction (ive been trying for the last 3 hours 💀)

IT ALWAYS OUTPUTS EITHER:

Traceback (most recent call last):
  File "/home/runner/test11112222/main.py", line 7, in <module>
    details = fr_api.get_flight_details(flight="-i put everything possible in here-")
  File "/home/runner/test11112222/.pythonlibs/lib/python3.10/site-packages/FlightRadar24/api.py", line 297, in get_flight_details
    response = APIRequest(Core.flight_data_url.format(flight.id),
AttributeError: 'str' object has no attribute 'id'

OR:

Traceback (most recent call last):
  File "/home/runner/test11112222/main.py", line 7, in <module>
    details = fr_api.get_flight_details(flight_id="-i put everything possible in here-")
TypeError: FlightRadar24API.get_flight_details() got an unexpected keyword argument 'flight_id'

sorry if this is obviously easy to fix but im kind of new to python and i just cant get it to work. 
thanks for the help in advance!

**Comment by JeanExtreme002** [comment]
The method receives a flight instance. Example:
```
flights = fr_api.get_flights()  # Returns a list of Flight objects
flight = flights[0]  # The first flight

flight_details = fr_api.get_flight_details(flight)
```
