### ISSUE TITLE
Is it normal that Python lib version 1.3.26 is documented in READMEs, in __init__.py, but isn't available on pypi ? 

### ISSUE THREAD

**Issue by opskov** [JeanExtreme002/FlightRadarAPI#63]
**Is your problem described in the documentation? If so, please describe**

I am quite interested in the latest "history data" feature described here: https://github.com/JeanExtreme002/FlightRadarAPI/tree/main/python#downloading-flight-data

However when pip installing the (obviously Python) library, I see that this functionality is missing in the Api class (checked the source code to confirm), and that the latest version accessible on Pypi is `1.3.25`, despite `1.3.26` being apparently released as per https://github.com/JeanExtreme002/FlightRadarAPI/blob/main/python/FlightRadar24/__init__.py

**Describe your question**

Considering the recent commits timestamps I was wondering whether it is normal that `1.3.26` is not installable via Pypi yet despite its functionalities being documented ?

**Steps to reproduce the behavior:**

1. Create a new Python virtualenv
2. Activate newly created virtualenv
3. Run `pip install FlightRadarAPI==1.3.26`

**Comment by JeanExtreme002** [comment]
Yes. Unfortunately, I didn't have the time to do some tests on the new feature. Next week I can release it to Pypi.

**Comment by opskovitch** [comment]
Thanks for the reply ! :) do you need any help with contributions ? I have some spare time these days

**Comment by JeanExtreme002** [comment]
> Thanks for the reply ! :) do you need any help with contributions ? I have some spare time these days

If you have knowledge in NodeJS, I would be glad if you could take a look at the return of method `getHistoryData()`. I marked the problem with a comment TODO.
