### ISSUE TITLE
Limit when retrieving departures and arrivals

### ISSUE THREAD

**Issue by eduardolfULPGC2003** [JeanExtreme002/FlightRadarAPI#64]
First of all thank you for the library, it is very useful. But I would like to ask why there is a limit of 100 flights when retrieving the departures or arrivals for a given airport. I would therefore suggest the possibility for this number being higher or at least the option (I sincerely do not know whether if it is even posible) to have a kind of offset so that if you cannot retrieve all the information at once you could eventually get it by doing several requests with different offsets (please let me know if I am not explaining myself).

Thank you again and kind regards.

**Comment by JeanExtreme002** [comment]
Hi Eduardo!

The limit is set by the internal api of flightradar24 website. This SDK just retrives the data from there. For this reason, there is nothing we can do for now but doing several requests.
