### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'items'

### ISSUE THREAD

**Issue by caro-acdm** [JeanExtreme002/FlightRadarAPI#69]
**Describe the bug**
The python script unexpectedly stops with this error. I have been using the api for a month, but this error is as recent as 23/04/2024. 

Portion of error:
--------------------------------------------------------------
  File "D:\Pxxx_Dxxx\Lib\site-packages\FlightRadar24\api.py", line 314, in get_flights
    for flight_id, flight_info in response.items():
                                  ^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'items'

--------------------------------------------------------------

**System (please complete the following information):**
 - OS: Windows
 - Python Version 12.2

**Comment by JeanExtreme002** [comment]
Could you try to reproduce this error again, executing the same steps you have done, and insert a `print(response)` to the code, before that line?

**Comment by caro-acdm** [comment]
I tried printing the response, but haven't been able to reproduce the attribute error yet. I will post as soon as I am able to catch it. I am currently using try-except to catch the attribute error.

**Comment by JeanExtreme002** [comment]
I'm closing this issue for now. If you have more information about the problem, please reopen the issue and send it here so I can help you.
