### ISSUE TITLE
How to set config?

### ISSUE THREAD

**Issue by k3im** [JeanExtreme002/FlightRadarAPI#7]
I want to modify one of the keys in the config dict but fail to do so. I even fail to feed back the read out parameters the following way (not exactly as shown in the documentation but how else can I call the set method?):
`params = fr_api.get_real_time_flight_tracker_config()`
`fr_api.set_real_time_flight_tracker_config(params)`

I get the following error:
TypeError: set_real_time_flight_tracker_config() takes 1 positional argument but 2 were given

Maybe I am not using your class correctly, but seems like I am giving only 1 positional argument. Could you give me a pointer on how to correctly feed in the config dictionary? Thanks!

**Comment by JeanExtreme002** [comment]
You must unpack your dict when calling the function, like this:

```
params = fr_api.get_real_time_flight_tracker_config()
fr_api.set_real_time_flight_tracker_config(**params)
```

**Comment by k3im** [comment]
Thanks for your quick reply! This was the problem and now it works.
