### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by DishanthM** [JeanExtreme002/FlightRadarAPI#72]
In several methods, like for example "get_flight_details", it says "object not found"'

**Expected behavior**
 I expected that it would give me details about the flight (I did it with a for loop).

System:
 - OS: [Windows 11]
 - Python Version [3.12]

**Comment by JeanExtreme002** [comment]
Could you show me your code and the query you are doing? Is this error still happening?

**Comment by JeanExtreme002** [comment]
I'm closing this issue for now. If you have more information about the problem, please reopen the issue and send it here so I can help you.
