### ISSUE TITLE
Aircraft coordinates accuracy (decimal places)

### ISSUE THREAD

**Issue by EugIva** [JeanExtreme002/FlightRadarAPI#76]
I have a question regarding the accuracy of the current aircraft coordinates. 

I have found that the accuracy of the coordinates depends on the radius that is being read, which is not satisfactory for my needs.
**Is it possible to obtain more accurate data, similar to what is displayed on the FL24?** 
 
For my project, I need to track the flight data of a single aircraft. I have set a zone within which its entire route will occur (from city to city) and am only receiving **two** precision digits. In order to obtain at least **four** characters, I would need to create very small zones. 
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145147798/3b6d7ccf-11db-4c2f-b6d8-9bc7a6d18df5)

( 2 zones - small and big)
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145147798/c7fa60e5-bdd6-4516-873d-8bb7cea20da7) ![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145147798/587e84cf-5e79-4e66-a895-c922ec4e7f7d) ![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145147798/2631afe5-0ec1-4e10-adbc-814177bd1994)

After exploring the **flight_detail** keys, I discovered a wealth of information, but unfortunately, I did not find the data I required. _Perhaps there is already complete information about the aircraft's traveled path with all relevant details, including the last recorded coordinates and even the entire trajectory up to the present moment?_

By the way, I was able to get something similar to what I needed using the "**trail**" key, but I still didn't understand what it meant, and there were no current coordinates for the aircraft. 

(example log for another aircraft)
![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145147798/ba88b9fc-dc02-4f2c-9671-0a6e13ea2078)

 I would appreciate your advice, I really need some help. 
 Thanks

**Comment by wvzack** [comment]
Question #31 solved this I would recommend reading it (also how were you able to get the lat/long of an aircraft)

**Comment by JeanExtreme002** [comment]
Sorry for taking too long to answer. I'm quite busy now.

This problem was solved on issue #55 
Closing this issue now.

**Comment by wvzack** [comment]
I am pretty sure they wanted to know if there was an alternative way to get the current position of the aircraft other then the trail.
