### ISSUE TITLE
Initialize instance FR with login

### ISSUE THREAD

**Issue by vdbosschekoen** [JeanExtreme002/FlightRadarAPI#82]
Since the new version (1.3.32) released on 2/8/2024 there is an issue when you want to create an instance of the flightradar API using an user and password to use your own flightradar account.

```py
from FlightRadar24 import FlightRadar24API
fr_api = FlightRadar24API(user=myuser,password=mypassword)
```
Then you receive the error 
AttributeError: 'FlightRadar24API' object has no attribute 'timeout'

I think the issue is in the class FlightRadar24API
The line ``` self.timeout: int = timeout ``` 
must be placed before the login call, because the login function is using the timeout variable and this will be set after the login.

**Comment by JeanExtreme002** [comment]
Fixed. Thank you for your report!
