### ISSUE TITLE
Trouble understanding how to use bounds

### ISSUE THREAD

**Issue by wvzackscratch** [JeanExtreme002/FlightRadarAPI#83]
In the documentation it says you may use a custom rectangle and says how however when I tried doing what I understood it didn't work. 
Here's my script:
`custom_bounds = "-84.452015,33.634585,-84.403603,33.634836"
	flights = fr_api.get_flights(bounds=custom_bounds)`
While this script is not producing an error it is returning `[]` and when i look on flightradar24 there is an large amount of aircraft on the runway
I am most likely doing this completely wrong. (this bbox is over runway 9L 27R at katl)

1. OS: Bookworm (Raspberry Pi)
2. Python Version: 3.11

Thanks!!!

**Comment by JeanExtreme002** [comment]
Maybe the format is wrong. Check the issue #1

You may even try using the method `get_bounds_by_point`, this way:

```
# Your point is 52°34'04.7"N 13°16'57.5"E from Google Maps and radius 2km
bounds = fr_api.get_bounds_by_point(52.567967, 13.282644, 2000)
```

**Comment by wvzackscratch** [comment]
I looked at that issue on and everything was right.

Here it says you can get a bound that's a rectangle however what I interpreted the instructions as did not work.

`# You may also set a custom region, such as: bounds = "73,-12,-156,38"
zone = fr_api.get_zones()["northamerica"]
bounds = 

 fr_api.get_bounds(zone)`

Could you please attach an example of how you can get the flights in a rectangle?

**Comment by JeanExtreme002** [comment]
Your bounds format is wrong. Try it: `"33.684954328581924,33.59502218948449,-84.4839828741172,-84.3759607152005"`

**Comment by wvzack** [comment]
thanks this worked!
